import { Scanne } from '../@types/scanne.type';
import { Providers } from './Providers';
import './global.css';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const scanne = await fetch('http://localhost:4001/api/main', {
    method: 'GET',
    cache: 'no-store',
  });

  console.log('SCANNNE', scanne);

  const result = (await scanne?.json()) as Scanne;
  return (
    <html lang="en">
      <body>
        <Providers scanProvider={{ scan: result }}>{children}</Providers>
      </body>
    </html>
  );
}
